const images = [
  // require('@components/loader/images/8.jpg'),
  // require('@components/loader/images/9.jpg'),
  // require('@components/loader/images/14.jpg'),
  // require('@components/loader/images/23.jpg'),
  // require('@components/loader/images/25.jpg'),
  // require('@components/loader/images/26.jpg'),
  // require('@components/loader/images/27.jpg'),
  // require('@components/loader/images/28.jpg'),
  // require('@components/loader/images/29.jpg'),
  // require('@components/loader/images/30.jpg'),

  require('@components/loader/images/1.jpg'),
  require('@components/loader/images/2.jpg'),
  require('@components/loader/images/3.jpg'),
  require('@components/loader/images/4.jpg'),
  require('@components/loader/images/5.jpg'),
  require('@components/loader/images/6.jpg'),
  require('@components/loader/images/7.jpg'),
  require('@components/loader/images/8.jpg'),
  require('@components/loader/images/9.jpg'),
  require('@components/loader/images/10.jpg'),
  require('@components/loader/images/11.jpg'),
  require('@components/loader/images/12.jpg'),
  require('@components/loader/images/13.jpg'),
  require('@components/loader/images/14.jpg'),
  require('@components/loader/images/15.jpg'),
  require('@components/loader/images/16.jpg'),
  require('@components/loader/images/17.jpg'),
  require('@components/loader/images/18.jpg'),
  require('@components/loader/images/19.jpg'),
  require('@components/loader/images/20.jpg'),
];

export default images;
