const images = [
  // require('@components/loader/images/8.jpg'),
  // require('@components/loader/images/9.jpg'),
  // require('@components/loader/images/14.jpg'),
  // require('@components/loader/images/23.jpg'),
  // require('@components/loader/images/25.jpg'),
  // require('@components/loader/images/26.jpg'),
  // require('@components/loader/images/27.jpg'),
  // require('@components/loader/images/28.jpg'),
  // require('@components/loader/images/29.jpg'),
  // require('@components/loader/images/30.jpg'),

  require('@components/hero/images/21.jpg'),
  require('@components/hero/images/22.jpg'),
  require('@components/hero/images/23.jpg'),
  require('@components/hero/images/24.jpg'),
  require('@components/hero/images/25.jpg'),
  require('@components/hero/images/26.jpg'),
  require('@components/hero/images/27.jpg'),
  require('@components/hero/images/28.jpg'),
  require('@components/hero/images/29.jpg'),
  require('@components/hero/images/30.jpg'),
  require('@components/hero/images/31.jpg'),
  require('@components/hero/images/1.jpg'),
  require('@components/hero/images/2.jpg'),
  require('@components/hero/images/3.jpg'),
  require('@components/hero/images/4.jpg'),
  require('@components/hero/images/5.jpg'),
  require('@components/hero/images/6.jpg'),
  require('@components/hero/images/7.jpg'),
  require('@components/hero/images/8.jpg'),
  require('@components/hero/images/9.jpg'),
  require('@components/hero/images/10.jpg'),
  require('@components/hero/images/11.jpg'),
  require('@components/hero/images/12.jpg'),
  require('@components/hero/images/13.jpg'),
  require('@components/hero/images/14.jpg'),
  require('@components/hero/images/15.jpg'),
  require('@components/hero/images/16.jpg'),
  require('@components/hero/images/17.jpg'),
  require('@components/hero/images/18.jpg'),
  require('@components/hero/images/19.jpg'),
  require('@components/hero/images/20.jpg'),

];

export default images;
